BlowOut/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    [Table("Rentals")]
    public class Rental
    {
        [Key]
        public int rentalID { get; set; }
        [DisplayName("Instrument")]
        public string RentalName { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
        public string Picture { get; set; }
        public int ClientID { get; set; }
    }
}

BlowOut/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class ClientsController : Controller
    {
        private BlowOutContext db = new BlowOutContext();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.Clients.ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create(int ID)
        {
            //TempData["RentalID"] = ID;
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClientID,FirstName,LastName,Address,City,State,Zip,Email,Phone")] Client client, int ID)
        {
            if (ModelState.IsValid)
            {
                client.ClientID = db.Clients.Count() + 1;
                db.Clients.Add(client);
                db.Rentals.Find(ID).ClientID = client.ClientID;
                db.SaveChanges();
                return RedirectToAction("Summary", new { RentalID = ID, ClientsID = client.ClientID});
            }

            return View(client);
        }

        public ActionResult Summary(int RentalID, int ClientsID)
        {
            ViewBag.Name = db.Clients.Find(ClientsID).FirstName;
            Rental rental = db.Rentals.Find(RentalID);
            return View(rental);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClientID,FirstName,LastName,Address,City,State,Zip,Email,Phone")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlowOut.DAL;
using BlowOut.Models;

namespace BlowOut.Controllers
{
    public class RentalsController : Controller
    {
        private BlowOutContext db = new BlowOutContext();

        // GET: Rentals
        public ActionResult Index()
        {
            return View(db.Rentals.ToList());
        }

        public ActionResult AddClient(int id)
        {
            Rental_Client rentalclient = new Rental_Client();

            rentalclient.rental = db.Rentals.Find(id);
            ViewBag.Names = db.Clients.ToList();
            return View(rentalclient);
        }

        [HttpPost]
        public ActionResult AddClient(Rental_Client rentalclient)
        {
            rentalclient.client = db.Clients.Find(rentalclient.rental.ClientID);

            return View();
        }

        // GET: Rentals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rental rental = db.Rentals.Find(id);
            if (rental == null)
            {
                return HttpNotFound();
            }
            return View(rental);
        }

        // GET: Rentals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rentals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "rentalID,RentalName,Type,Price,Picture,ClientID")] Rental rental)
        {
            if (ModelState.IsValid)
            {
                db.Rentals.Add(rental);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rental);
        }

        // GET: Rentals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rental rental = db.Rentals.Find(id);
            if (rental == null)
            {
                return HttpNotFound();
            }
            return View(rental);
        }

        // POST: Rentals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "rentalID,RentalName,Type,Price,Picture,ClientID")] Rental rental)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rental).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rental);
        }

        // GET: Rentals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rental rental = db.Rentals.Find(id);
            if (rental == null)
            {
                return HttpNotFound();
            }
            return View(rental);
        }

        // POST: Rentals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rental rental = db.Rentals.Find(id);
            db.Rentals.Remove(rental);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlowOut/Views/Rentals/AddClient.cshtml
@model BlowOut.Models.Rental_Client
@{
    ViewBag.Title = "AddClient";
}

<h2>Add Client to @Html.DisplayFor(model => model.rental.RentalName) </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Owner for the Car</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.rental.rentalID)
    @Html.HiddenFor(model => model.rental.RentalName)
    @Html.HiddenFor(model => model.rental.Type)
    @Html.HiddenFor(model => model.rental.Price)
    @Html.HiddenFor(model => model.rental.Picture)
  

    <div class="form-group">
        Renting Client
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.rental.ClientID, new SelectList(ViewBag.Names, "ClientID", "FirstName"))
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Add Owner" class="btn btn-default" />
        </div>
    </div>
</div>
}

BlowOut/Views/Rentals/Create.cshtml
@model BlowOut.Models.Rental

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rental</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RentalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RentalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RentalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlowOut/Views/Rentals/Delete.cshtml
@model BlowOut.Models.Rental

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rental</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RentalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlowOut/Views/Rentals/Details.cshtml
@model BlowOut.Models.Rental

@{
    ViewBag.Title = "Details";
}

<h2>Details for @Html.DisplayFor(model => model.RentalName)</h2>

<div>
    <hr />
    <img src="@Html.DisplayFor(model => model.Picture)" alt="@Html.DisplayNameFor(model => model.Picture)" style="width:30%;" align="left" />
    <br clear="right" />
    <div>

        <p>
            <strong>@Html.DisplayNameFor(model => model.RentalName)</strong>
        </p>

        <p>
            @Html.DisplayFor(model => model.RentalName)
        </p>

        <div style="display: inline-block">
            <p><strong>New Price</strong></p>
            <input type="checkbox" name="NewPrice" value="new" id="newCheck" />
        </div>
        <div style="display: inline-block">
            <p><strong>Used Price</strong></p>
            <input type="checkbox" name="UsedPrice" value="used" id="usedCheck" />
        </div>

        <div style="display: none" id="newText">
            <p>
                New: $@Html.DisplayFor(model => model.Type)
            </p>
        </div>

        <div style="display: none" id="usedText">

            <p>
                Used: $@Html.DisplayFor(model => model.Price)
            </p>
        </div>

    </div>
</div>
<br />
<br />
<br />
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<p>
    @Html.ActionLink("Rent this Instrument", "Create", "Clients", new { id = Model.rentalID }, null)
</p>
<p>
    @Html.ActionLink("Add Renter", "AddClient", new { id = Model.rentalID })
</p>
<p>
    Current renter is Customer #@Html.DisplayFor(model => model.ClientID)
</p>

<script type="text/javascript">
    var newCheck = document.getElementById("newCheck")
    var usedCheck = document.getElementById("usedCheck")
    newCheck.addEventListener('change', newClick)
    usedCheck.addEventListener('change', usedClick)
    function newClick() {
        if (newCheck.checked == true) {
            document.getElementById("newText").style.display = "block"
        }
        else {
            document.getElementById("newText").style.display = "none"
        }
    }
    function usedClick() {
        if (usedCheck.checked == true) {
            document.getElementById("usedText").style.display = "block"
        }
        else {
            document.getElementById("usedText").style.display = "none"
        }
    }
</script>

BlowOut/Views/Rentals/Edit.cshtml
@model BlowOut.Models.Rental

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rental</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.rentalID)

        <div class="form-group">
            @Html.LabelFor(model => model.RentalName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RentalName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RentalName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BlowOut/Views/Rentals/Index.cshtml
@model IEnumerable<BlowOut.Models.Rental>

@{
    ViewBag.Title = "Index";
}

<h2>Instrument Rentals</h2>
<br />
<div class="container" style="display: flex; flex-wrap: wrap;">
    <div class="row text-center">
        @foreach (var item in Model)
        {
            <div class="col-md-3 col-sm-6">
                <div class="thumbnail">
                    <img src="@item.Picture" />
                    <div class="caption">
                        <h4>@item.RentalName</h4>
                        <br />
                        @Html.ActionLink("Details", "Details", new { id = item.rentalID })
                    </div>
                </div>
            </div>
        }
    </div>
</div>